import { prisma } from "@/lib/db/prisma";
import { Prisma } from "@prisma/client";
import { cache } from "react";
import { unstable_cache } from "next/cache";
import { discoTag } from "@/lib/cacheTags";

export type DiscoMeta = {
  disponivel: boolean;
  lastfmTags: string | null;
  lastfmListeners: number | null;
  lastfmPlaycount: number | null;
  lastfmWikiPt: string | null;
  sobrePt: string | null;
  sobrePtSourceUrl: string | null;
  mbMbid: string | null;
  mbFirstReleaseDate: string | null;
  mbPrimaryType: string | null;
  mbGenres: string | null;
  mbTracklist: string | null;
  mbRating: number | null;
  mbRatingVotes: number | null;
  artistCountry: string | null;
  artistLastfmUrl: string | null;
  mbLabel: string | null;
  discogsTitle: string | null;
  discogsStyles: string | null;
  discogsCatno: string | null;
  discogsCountry: string | null;
  discogsMasterYear: number | null;
  discogsTracklist: unknown;
  mbCatalogNumber: string | null;
  mbBarcode: string | null;
  mbReleaseCountry: string | null;
  ean: string | null;
};

export type RelatedDeal = {
  id: string;
  titulo: string;
  artista: string;
  slug: string;
  imgUrl: string | null;
  url: string;
  marketplace: string;
  estilo: string | null;
  rating: string | null;
  precoAtual: number;
  mediaPreco: number;
  desconto: number;
  sparkline: unknown;
  dealScore: number | null;
  confidenceLevel: string | null;
};

// Two-layer cache:
// - unstable_cache: persists across requests/users, 30-min TTL, invalidated by
//   crawler webhook via the "prices" tag. Prevents the 252k/day cold DB hits
//   that were generated by React cache() which only deduplicates within one render.
// - React cache() wrapper: deduplicates the two calls within the same render
//   (generateMetadata + page component) so the unstable_cache is hit only once.
// Tagged per record rather than with the broad "prices" tag: a crawl observes
// ~4,200 of ~31,000 records, so a blanket purge marked ~27,000 untouched pages
// stale and paid to rebuild them. See lib/cacheTags.ts.
const _getDiscoWithPrecos = (slug: string) =>
  unstable_cache(
    async () => {
      const oneYearAgo = new Date(Date.now() - 365 * 24 * 60 * 60 * 1000);
      return prisma.disco.findUnique({
        where: { slug },
        include: {
          precos: {
            where: { capturadoEm: { gte: oneYearAgo } },
            orderBy: { capturadoEm: "asc" },
          },
        },
      });
    },
    ["disco-with-precos", slug],
    { tags: [discoTag(slug)], revalidate: 14400 },
  )();

// unstable_cache serializes to JSON — Prisma Date objects become strings.
// Re-hydrate capturadoEm back to Date so page components can call .toLocaleeDateString().
async function _getDiscoWithPrecosHydrated(slug: string) {
  const result = await _getDiscoWithPrecos(slug);
  if (!result) return null;
  return {
    ...result,
    precos: result.precos.map((p) => ({
      ...p,
      capturadoEm: new Date(p.capturadoEm),
    })),
  };
}
export const getDiscoWithPrecos = cache(_getDiscoWithPrecosHydrated);

// Wrapped in unstable_cache like the other disco reads: a bare prisma call here
// opts /disco/[slug] out of ISR entirely (route renders dynamic, Cache-Control:
// no-store, every Googlebot hit is an uncached SSR). Tagged per record —
// `disponivel` changes with each crawl, so the crawler purges discoTag(slug)
// for every record it observes.
export const getDiscoMeta = (slug: string) =>
  unstable_cache(
    async (): Promise<DiscoMeta | null> => {
    const rows = await prisma.$queryRaw<[DiscoMeta]>`
      SELECT
        disponivel,
        lastfm_tags      AS "lastfmTags",
        lastfm_listeners AS "lastfmListeners",
        lastfm_playcount AS "lastfmPlaycount",
        lastfm_wiki_pt   AS "lastfmWikiPt",
        sobre_pt         AS "sobrePt",
        sobre_pt_source_url AS "sobrePtSourceUrl",
        mb_mbid                AS "mbMbid",
        mb_first_release_date  AS "mbFirstReleaseDate",
        mb_primary_type        AS "mbPrimaryType",
        mb_genres              AS "mbGenres",
        mb_tracklist           AS "mbTracklist",
        mb_rating              AS "mbRating",
        mb_rating_votes        AS "mbRatingVotes",
        am.country             AS "artistCountry",
        -- Canonical Last.fm artist URL as MusicBrainz records it. The disco
        -- page used to build this from our own artista string, which is the
        -- Amazon-derived spelling and does not always match Last.fm's.
        am.mb_urls->'last.fm'->>0 AS "artistLastfmUrl",
        -- Pressing-level fields. NULL on ~57% of records by design: they are
        -- only stored when the MusicBrainz release-group leaves no doubt (one
        -- release, or every release sharing the same label). See
        -- crawler/fetch_release_details.py.
        d.mb_label             AS "mbLabel",
        -- Discogs resolves the record to an exact pressing via its barcode, so
        -- these describe the disc Amazon actually sells. The tracklist in
        -- particular is the VINYL running order with side positions; mb_tracklist
        -- is the release-group's representative release and is frequently the CD
        -- (Castle in the Sky: 23 tracks on MB, 14 on the LP).
        d.discogs_title        AS "discogsTitle",
        d.discogs_styles       AS "discogsStyles",
        d.discogs_catno        AS "discogsCatno",
        d.discogs_country      AS "discogsCountry",
        d.discogs_master_year  AS "discogsMasterYear",
        d.discogs_tracklist    AS "discogsTracklist",
        d.mb_catalog_number    AS "mbCatalogNumber",
        d.mb_barcode           AS "mbBarcode",
        d.mb_release_country   AS "mbReleaseCountry",
        d.ean                  AS "ean"
      FROM "Disco" d
      LEFT JOIN "ArtistMeta" am ON am.artista = d.artista
      WHERE d.slug = ${slug}
    `;
      return rows[0] ?? null;
    },
    ["disco-meta", slug],
    { tags: [discoTag(slug)], revalidate: 14400 },
  )();

// Build-time only (generateStaticParams) — not wrapped in unstable_cache since
// it runs once per deploy, not per-request. Ranks by real crawler-recorded
// traffic (bot_hits) rather than lastfm_listeners, so it prioritizes the pages
// Googlebot/bots actually hit, independent of a record's popularity elsewhere.
export async function getTopBotHitSlugs(pathPrefix: string, limit: number): Promise<string[]> {
  // The (::int) cast is load-bearing: without it, Postgres can't infer the
  // parameter's type and picks the regex-match `substring(text, pattern)`
  // overload instead of the position-based one, silently returning NULL (or
  // a bogus regex match) for almost every row instead of the real slug.
  const rows = await prisma.$queryRaw<{ slug: string }[]>`
    SELECT substring(path from (${pathPrefix.length + 1})::int) AS slug, count(*) AS hits
    FROM bot_hits
    WHERE path LIKE ${pathPrefix + "%"}
    GROUP BY slug
    ORDER BY hits DESC
    LIMIT ${limit}
  `;
  return rows.map((r) => r.slug);
}

export const getArtistPopularity = (artista: string, slug: string) =>
  unstable_cache(
    async (): Promise<{ rank: number; total: number } | null> => {
    const rows = await prisma.$queryRaw<{ rank: bigint; total: bigint }[]>`
      WITH ranked AS (
        SELECT slug,
               RANK() OVER (ORDER BY lastfm_listeners DESC) AS rank,
               COUNT(*) OVER ()                             AS total
        FROM "Disco"
        WHERE artista = ${artista}
          AND (format IS NULL OR format = 'vinyl')
          AND lastfm_listeners > 0
      )
      SELECT rank, total FROM ranked WHERE slug = ${slug} LIMIT 1
    `;
      const r = rows[0];
      return r ? { rank: Number(r.rank), total: Number(r.total) } : null;
    },
    ["artist-popularity", artista, slug],
    { tags: [discoTag(slug)], revalidate: 14400 },
  )();

export const getRelatedDeals = (discoId: string, slug: string, tags: string[]) =>
  unstable_cache(
    async (): Promise<RelatedDeal[]> => {
    // Lowercase tags to match the GIN index expression: string_to_array(lower(lastfm_tags), ', ')
    const lowerTags = tags.map((t) => t.toLowerCase());
    const tagFilter = lowerTags.length > 0
      ? Prisma.sql`AND string_to_array(lower(lastfm_tags), ', ') && ARRAY[${Prisma.join(lowerTags)}]::text[]`
      : Prisma.empty;
    return prisma.$queryRaw<RelatedDeal[]>`
      WITH candidates AS (
        SELECT id, titulo, artista, slug, "imgUrl", url, marketplace, estilo, rating,
               deal_score, confidence_level, avg_30d
        FROM "Disco"
        WHERE id != ${discoId}
          AND deal_score IS NOT NULL
          AND disponivel = TRUE
          AND (format IS NULL OR format = 'vinyl')
          AND price_count >= 5
          ${tagFilter}
        ORDER BY deal_score DESC, RANDOM()
        LIMIT 4
      )
      SELECT
        c.id,
        c.titulo,
        c.artista,
        c.slug,
        c."imgUrl",
        c.url,
        c.marketplace,
        c.estilo,
        c.rating,
        c.deal_score                                         AS "dealScore",
        c.confidence_level                                   AS "confidenceLevel",
        l.preco                                              AS "precoAtual",
        COALESCE(c.avg_30d::float, l.preco)                  AS "mediaPreco",
        CASE
          WHEN COALESCE(c.avg_30d::float, 0) > 0
          THEN (COALESCE(c.avg_30d::float, l.preco) - l.preco) / COALESCE(c.avg_30d::float, l.preco)
          ELSE 0
        END                                                  AS desconto,
        (
          SELECT COALESCE(
            json_agg(sp."precoBrl"::float ORDER BY sp."capturadoEm"),
            '[]'::json
          )
          FROM (
            SELECT "precoBrl", "capturadoEm"
            FROM   "HistoricoPreco"
            WHERE  "discoId" = c.id
              AND  "capturadoEm" >= NOW() - INTERVAL '30 days'
            ORDER  BY "capturadoEm" ASC
            LIMIT  10
          ) sp
        ) AS sparkline
      FROM candidates c
      JOIN LATERAL (
        SELECT "precoBrl"::float AS preco
        FROM "HistoricoPreco"
        WHERE "discoId" = c.id
        ORDER BY "capturadoEm" DESC
        LIMIT 1
      ) l ON TRUE
    `;
  },
    ["disco-related-deals", discoId],
    { tags: [discoTag(slug)], revalidate: 14400 },
  )();

export const getArtistTopAlbums = (artista: string, discoId: string, slug: string) =>
  unstable_cache(
    async (): Promise<RelatedDeal[]> => {
    return prisma.$queryRaw<RelatedDeal[]>`
      WITH candidates AS (
        SELECT id, titulo, artista, slug, "imgUrl", url, marketplace, estilo, rating,
               deal_score, confidence_level, avg_30d
        FROM "Disco"
        WHERE artista = ${artista}
          AND id != ${discoId}
          AND disponivel = TRUE
          AND (format IS NULL OR format = 'vinyl')
          AND price_count >= 5
        ORDER BY lastfm_listeners DESC NULLS LAST, RANDOM()
        LIMIT 4
      )
      SELECT
        c.id, c.titulo, c.artista, c.slug, c."imgUrl", c.url, c.marketplace, c.estilo, c.rating,
        c.deal_score                                         AS "dealScore",
        c.confidence_level                                   AS "confidenceLevel",
        l.preco                                              AS "precoAtual",
        COALESCE(c.avg_30d::float, l.preco)                  AS "mediaPreco",
        CASE
          WHEN COALESCE(c.avg_30d::float, 0) > 0
          THEN (COALESCE(c.avg_30d::float, l.preco) - l.preco) / COALESCE(c.avg_30d::float, l.preco)
          ELSE 0
        END                                                  AS desconto,
        (
          SELECT COALESCE(json_agg(sp."precoBrl"::float ORDER BY sp."capturadoEm"), '[]'::json)
          FROM (
            SELECT "precoBrl", "capturadoEm"
            FROM   "HistoricoPreco"
            WHERE  "discoId" = c.id AND "capturadoEm" >= NOW() - INTERVAL '30 days'
            ORDER  BY "capturadoEm" ASC LIMIT 10
          ) sp
        ) AS sparkline
      FROM candidates c
      JOIN LATERAL (
        SELECT "precoBrl"::float AS preco
        FROM "HistoricoPreco"
        WHERE "discoId" = c.id
        ORDER BY "capturadoEm" DESC LIMIT 1
      ) l ON TRUE
    `;
  },
    ["disco-artist-top-albums", artista, discoId],
    { tags: [discoTag(slug)], revalidate: 14400 },
  )();


