import { prisma } from "@/lib/db/prisma";
import { Prisma } from "@prisma/client";
import { cache } from "react";
import { unstable_cache } from "next/cache";

export type DiscoMeta = {
  disponivel: boolean;
  lastfmTags: string | null;
  lastfmListeners: number | null;
  lastfmPlaycount: number | null;
  lastfmWikiPt: string | null;
};

export type RelatedDeal = {
  id: string;
  titulo: string;
  artista: string;
  slug: string;
  imgUrl: string | null;
  url: string;
  estilo: string | null;
  rating: string | null;
  precoAtual: number;
  mediaPreco: number;
  desconto: number;
  sparkline: unknown;
  dealScore: number | null;
  confidenceLevel: string | null;
};

// Two-layer cache:
// - unstable_cache: persists across requests/users, 30-min TTL, invalidated by
//   crawler webhook via the "prices" tag. Prevents the 252k/day cold DB hits
//   that were generated by React cache() which only deduplicates within one render.
// - React cache() wrapper: deduplicates the two calls within the same render
//   (generateMetadata + page component) so the unstable_cache is hit only once.
const _getDiscoWithPrecos = unstable_cache(
  async (slug: string) => {
    const oneYearAgo = new Date(Date.now() - 365 * 24 * 60 * 60 * 1000);
    return prisma.disco.findUnique({
      where: { slug },
      include: {
        precos: {
          where: { capturadoEm: { gte: oneYearAgo } },
          orderBy: { capturadoEm: "asc" },
        },
      },
    });
  },
  ["disco-with-precos"],
  { tags: ["prices"], revalidate: 86400 },
);

// unstable_cache serializes to JSON — Prisma Date objects become strings.
// Re-hydrate capturadoEm back to Date so page components can call .toLocaleeDateString().
async function _getDiscoWithPrecosHydrated(slug: string) {
  const result = await _getDiscoWithPrecos(slug);
  if (!result) return null;
  return {
    ...result,
    precos: result.precos.map((p) => ({
      ...p,
      capturadoEm: new Date(p.capturadoEm),
    })),
  };
}
export const getDiscoWithPrecos = cache(_getDiscoWithPrecosHydrated);

// Wrapped in unstable_cache like the other disco reads: a bare prisma call here
// opts /disco/[slug] out of ISR entirely (route renders dynamic, Cache-Control:
// no-store, every Googlebot hit is an uncached SSR). Tagged "prices" because
// `disponivel` changes with each crawl, so revalidateTag("prices") refreshes it.
export const getDiscoMeta = unstable_cache(
  async (slug: string): Promise<DiscoMeta | null> => {
    const rows = await prisma.$queryRaw<[DiscoMeta]>`
      SELECT
        disponivel,
        lastfm_tags      AS "lastfmTags",
        lastfm_listeners AS "lastfmListeners",
        lastfm_playcount AS "lastfmPlaycount",
        lastfm_wiki_pt   AS "lastfmWikiPt"
      FROM "Disco" WHERE slug = ${slug}
    `;
    return rows[0] ?? null;
  },
  ["disco-meta"],
  { tags: ["prices"], revalidate: 86400 },
);

export const getRelatedDeals = unstable_cache(
  async (discoId: string, tags: string[]): Promise<RelatedDeal[]> => {
    // Lowercase tags to match the GIN index expression: string_to_array(lower(lastfm_tags), ', ')
    const lowerTags = tags.map((t) => t.toLowerCase());
    const tagFilter = lowerTags.length > 0
      ? Prisma.sql`AND string_to_array(lower(lastfm_tags), ', ') && ARRAY[${Prisma.join(lowerTags)}]::text[]`
      : Prisma.empty;
    return prisma.$queryRaw<RelatedDeal[]>`
      WITH candidates AS (
        SELECT id, titulo, artista, slug, "imgUrl", url, estilo, rating,
               deal_score, confidence_level, avg_30d
        FROM "Disco"
        WHERE id != ${discoId}
          AND deal_score IS NOT NULL
          AND disponivel = TRUE
          AND (format IS NULL OR format = 'vinyl')
          AND price_count >= 5
          ${tagFilter}
        ORDER BY deal_score DESC, RANDOM()
        LIMIT 4
      )
      SELECT
        c.id,
        c.titulo,
        c.artista,
        c.slug,
        c."imgUrl",
        c.url,
        c.estilo,
        c.rating,
        c.deal_score                                         AS "dealScore",
        c.confidence_level                                   AS "confidenceLevel",
        l.preco                                              AS "precoAtual",
        COALESCE(c.avg_30d::float, l.preco)                  AS "mediaPreco",
        CASE
          WHEN COALESCE(c.avg_30d::float, 0) > 0
          THEN (COALESCE(c.avg_30d::float, l.preco) - l.preco) / COALESCE(c.avg_30d::float, l.preco)
          ELSE 0
        END                                                  AS desconto,
        (
          SELECT COALESCE(
            json_agg(sp."precoBrl"::float ORDER BY sp."capturadoEm"),
            '[]'::json
          )
          FROM (
            SELECT "precoBrl", "capturadoEm"
            FROM   "HistoricoPreco"
            WHERE  "discoId" = c.id
              AND  "capturadoEm" >= NOW() - INTERVAL '30 days'
            ORDER  BY "capturadoEm" ASC
            LIMIT  10
          ) sp
        ) AS sparkline
      FROM candidates c
      JOIN LATERAL (
        SELECT "precoBrl"::float AS preco
        FROM "HistoricoPreco"
        WHERE "discoId" = c.id
        ORDER BY "capturadoEm" DESC
        LIMIT 1
      ) l ON TRUE
    `;
  },
  ["disco-related-deals"],
  { tags: ["prices"], revalidate: 86400 }
);
