// Artist-page title A/B test, started 2026-09-24.
//
// Record pages beat artist pages on CTR at matched positions (8-15) by 1-2
// points, most likely because they carry review stars that Google's spec bars
// from listing pages. The title is the one lever left. Group B tests a title
// built on "LP" + "na Amazon" instead of "Histórico de Preço" (0.7% of demand).
//
// Cohort: every artist page with >=30 impressions in GSC 2026-06-22..09-21
// (109 pages), sorted by impressions, paired, one of each pair to B at random
// (seed 428, the most balanced of 2,000 draws). Pre-period: A 6,065 imp / 1.95%
// CTR / pos 10.44; B 6,348 imp / 1.94% / pos 10.46.
//
// Measure after >=4 weeks (from ~2026-10-22): GSC page data for both lists,
// same window, CTR B vs A, and each group against its own pre-period.
// Then keep the winner for all artist pages and delete this file.

export const TITLE_TEST_VARIANT: ReadonlySet<string> = new Set([
  "abba",
  "alice-in-chains",
  "avril-lavigne",
  "bauhaus",
  "beastie-boys",
  "bjork",
  "black-sabbath",
  "brent-faiyaz",
  "britney-spears",
  "chappell-roan",
  "creed",
  "creedence-clearwater-revival",
  "crystal-castles",
  "demi-lovato",
  "depeche-mode",
  "elvis-presley",
  "fleetwood-mac",
  "florence-the-machine",
  "frank-sinatra",
  "frank-zappa",
  "genesis",
  "guns-n-roses",
  "heart",
  "him",
  "impaled",
  "iron-maiden",
  "jackson-5",
  "james-brown",
  "johnny-cash",
  "journey",
  "judas-priest",
  "justin-bieber",
  "kanye-west",
  "kate-bush",
  "kendrick-lamar",
  "lana-del-rey",
  "laura-pausini",
  "lorde",
  "mariah-carey",
  "mazzy-star",
  "michael-jackson",
  "nightwish",
  "rihanna",
  "santana",
  "sepultura",
  "shawn-mendes",
  "sleeping-with-sirens",
  "tame-impala",
  "the-notorious-b-i-g",
  "the-rolling-stones",
  "the-strokes",
  "travis-scott",
  "tyler-the-creator",
  "u2",
]);

// Control group: keeps the current title. Not read at runtime; listed so the
// measurement uses the exact same pages.
export const TITLE_TEST_CONTROL: readonly string[] = [
  "2pac",
  "aerosmith",
  "ariana-grande",
  "bad-omens",
  "billie-eilish",
  "blink-182",
  "blondie",
  "bon-jovi",
  "bts",
  "caetano-veloso",
  "chico-buarque",
  "current-joys",
  "dazey-and-the-scouts",
  "deep-purple",
  "dolly-parton",
  "dream-theater",
  "ed-sheeran",
  "elis-regina",
  "elton-john",
  "erasmo-carlos",
  "erykah-badu",
  "foo-fighters",
  "foreigner",
  "g-eazy",
  "ghost",
  "glass-animals",
  "green-day",
  "john-coltrane",
  "joji",
  "linkin-park",
  "maneskin",
  "marvin-gaye",
  "mayhem",
  "miley-cyrus",
  "mobb-deep",
  "muse",
  "nick-drake",
  "nirvana",
  "paramore",
  "pet-shop-boys",
  "sade",
  "simon-garfunkel",
  "star-wars",
  "stevie-wonder",
  "stray-kids",
  "the-1975",
  "the-cranberries",
  "the-who",
  "tim-maia",
  "tori-amos",
  "troye-sivan",
  "twenty-one-pilots",
  "van-halen",
  "war",
  "weezer",
];
