import { COUNTRY_TAG_TO_PAIS_SLUG } from "@/lib/paises";

/**
 * Final destination for every /estilo and /artista slug that next.config.ts
 * redirects, so link builders emit the target directly instead of routing
 * readers and crawlers through a 308. The crawl of 24 Aug 2026 found 759
 * internal links landing on a redirect; 332 of them were /estilo/synth-pop
 * alone.
 *
 * Keep in step with the redirects() block in next.config.ts -- the redirects
 * stay in place for external links and old bookmarks, this map only stops us
 * generating new links into them.
 */

/** Slug -> absolute path, for slugs redirected away from /estilo/<slug>. */
export const ESTILO_REDIRECT_TARGETS: Record<string, string> = {
  "60s": "/decada/1960",
  "70s": "/decada/1970",
  "80s": "/decada/1980",
  "8bit": "/estilo/8-bit",
  "90s": "/decada/1990",
  "afro-beat": "/estilo/afrobeat",
  "alan-jackson": "/artista/alan-jackson",
  "alternative-hiphop": "/estilo/alternative-hip-hop",
  "andrea-bocelli": "/artista/andrea-bocelli",
  "ariana-grande": "/artista/ariana-grande",
  "artpop": "/estilo/art-pop",
  "audio-book": "/estilo/audiobook",
  "avant-garde-pop": "/estilo/avantgarde-pop",
  "avantgarde": "/estilo/avant-garde",
  "avantgarde-jazz": "/estilo/avant-garde-jazz",
  "bauhaus": "/artista/bauhaus",
  "belchior": "/artista/belchior",
  "bigband": "/estilo/big-band",
  "blackpink": "/artista/blackpink",
  "blake-shelton": "/artista/blake-shelton",
  "bluesrock": "/estilo/blues-rock",
  "boy-band": "/estilo/boybands",
  "boyband": "/estilo/boybands",
  "britney-spears": "/artista/britney-spears",
  "bts": "/artista/bts",
  "celine-dion": "/artista/celine-dion",
  "chill-out": "/estilo/chillout",
  "chris-brown": "/artista/chris-brown",
  "cold-wave": "/estilo/coldwave",
  "contemporaryfolk": "/estilo/contemporary-folk",
  "cortis": "/artista/cortis",
  "cyber-punk": "/estilo/cyberpunk",
  "death-rock": "/estilo/deathrock",
  "doctor-who": "/artista/doctor-who",
  "dreampop": "/estilo/dream-pop",
  "electro-pop": "/estilo/electropop",
  "emopop": "/estilo/emo-pop",
  "eric-church": "/artista/eric-church",
  "euro-pop": "/estilo/europop",
  "exo": "/artista/exo",
  "fagner": "/artista/raimundo-fagner",
  "fleetwood-mac": "/artista/fleetwood-mac",
  "folkrock": "/estilo/folk-rock",
  "future": "/artista/future",
  "game-music": "/estilo/game",
  "game-remixes": "/estilo/game",
  "george-strait": "/artista/george-strait",
  "german-hip-hop": "/estilo/german-hiphop",
  "ginuwine": "/artista/ginuwine",
  "girl-group": "/estilo/girl-groups",
  "hannah-montana": "/artista/hannah-montana",
  "hard-core": "/estilo/hardcore",
  "hardbop": "/estilo/hard-bop",
  "helloween": "/artista/helloween",
  "hilary-duff": "/artista/hilary-duff",
  "hiphop": "/estilo/hip-hop",
  "hyper-pop": "/estilo/hyperpop",
  "indiepop": "/estilo/indie-pop",
  "jamband": "/estilo/jam-band",
  "jay-z": "/artista/jay-z",
  "jazzpiano": "/estilo/jazz-piano",
  "jim-hall": "/artista/jim-hall",
  "jimin": "/artista/jimin",
  "jpop": "/estilo/j-pop",
  "keith-urban": "/artista/keith-urban",
  "kenny-chesney": "/artista/kenny-chesney",
  "kenny-rogers": "/artista/kenny-rogers",
  "keyshia-cole": "/artista/keyshia-cole",
  "kpop": "/estilo/k-pop",
  "kraut-rock": "/estilo/krautrock",
  "latinjazz": "/estilo/latin-jazz",
  "little-big-town": "/artista/little-big-town",
  "lofi": "/estilo/lo-fi",
  "mash-up": "/estilo/mashup",
  "metallica": "/artista/metallica",
  "middle-of-the-road": "/artista/middle-of-the-road",
  "miranda-lambert": "/artista/miranda-lambert",
  "naruto": "/estilo/anime",
  "neo-classical-dark-wave": "/estilo/neoclassical-darkwave",
  "neo-folk": "/estilo/neofolk",
  "nujazz": "/estilo/nu-jazz",
  "oldschool-hardcore": "/estilo/old-school-hardcore",
  "one-direction": "/artista/one-direction",
  "one-piece": "/estilo/anime",
  "ost": "/estilo/soundtrack",
  "poprock": "/estilo/pop-rock",
  "powerpop": "/estilo/power-pop",
  "psy-trance": "/estilo/psytrance",
  "punkrock": "/estilo/punk-rock",
  "queen": "/artista/queen",
  "randy-travis": "/artista/randy-travis",
  "raspberry-bulbs": "/artista/raspberry-bulbs",
  "ray-conniff": "/artista/ray-conniff",
  "rb": "/estilo/r-b",
  "reba-mcentire": "/artista/reba-mcentire",
  "rockandroll": "/estilo/rock-and-roll",
  "rose": "/artista/rose",
  "shania-twain": "/artista/shania-twain",
  "sheena-easton": "/artista/sheena-easton",
  "showtunes": "/estilo/show-tunes",
  "singersongwriter": "/estilo/singer-songwriter",
  "spice-girls": "/artista/spice-girls",
  "standup-comedy": "/estilo/stand-up-comedy",
  "synth-pop": "/estilo/synthpop",
  "synth-wave": "/estilo/synthwave",
  "tanya-tucker": "/artista/tanya-tucker",
  "thrash-core": "/estilo/thrashcore",
  "tim-mcgraw": "/artista/tim-mcgraw",
  "toby-keith": "/artista/toby-keith",
  "triphop": "/estilo/trip-hop",
  "underground-hiphop": "/estilo/underground-hip-hop",
  "valve": "/estilo/game",
  "video-game-music": "/estilo/game",
  "west-coast-hiphop": "/estilo/west-coast-hip-hop",
  "within-temptation": "/artista/within-temptation",
};

/** Slug -> absolute path, for slugs redirected away from /artista/<slug>. */
export const ARTISTA_REDIRECT_TARGETS: Record<string, string> = {
  "alabama3": "/artista/alabama-3",
  "andr-s-schiff": "/artista/andras-schiff",
  "animate-invent": "/artista/invent-animate",
  "artists-various": "/artista/various-artists",
  "black-pink": "/artista/blackpink",
  "booker-t-the-m-g-s": "/artista/booker-t-the-mg-s",
  "brel-jacques": "/artista/jacques-brel",
  "brianauger-s-oblivion-express": "/artista/brian-auger-s-oblivion-express",
  "bunyan-vashti": "/artista/vashti-bunyan",
  "cruz-celia": "/artista/celia-cruz",
  "d-kat-von": "/artista/kat-von-d",
  "deathgrips": "/artista/death-grips",
  "doa": "/artista/d-o-a",
  "doma-molchat": "/artista/molchat-doma",
  "enuff-znuff": "/artista/enuff-z-nuff",
  "fraites-jeremiah": "/artista/jeremiah-fraites",
  "g-gus": "/artista/gus-g",
  "head-cat": "/artista/headcat",
  "inc-masta-ace": "/artista/masta-ace-incorporated",
  "jungkook": "/artista/jung-kook",
  "la-guns": "/artista/l-a-guns",
  "lady-gaga-joaquin-phoenix-cast-of-joker-folie-deux": "/artista/lady-gaga-joaquin-phoenix-cast-of-joker-folie-a-deux",
  "leadbelly": "/artista/lead-belly",
  "mar-a-due-as": "/artista/maria-duenas",
  "motley-cr-e": "/artista/motley-crue",
  "musicas-mp3": "/estilo/soundtrack",
  "nash-young-crosby-stills": "/artista/stills-nash-young-crosby",
  "nct127": "/artista/nct-127",
  "new-jeans": "/artista/newjeans",
  "noah-finnce": "/artista/noahfinnce",
  "original-soundtrack": "/estilo/soundtrack",
  "ork": "/artista/o-r-k",
  "ost": "/estilo/soundtrack",
  "the-creator-tyler": "/artista/tyler-the-creator",
  "the-jet-black-s": "/artista/the-jet-blacks",
  "varios": "/artista/various-artists",
  "varios-artistas": "/artista/various-artists",
  "various": "/artista/various-artists",
  "various-aritist": "/artista/various-artists",
  "various-artist": "/artista/various-artists",
  "vf": "/artista/nf",
  "willie-col-n": "/artista/willie-colon",
  "willie-col-n-celia-cruz": "/artista/willie-colon-celia-cruz",
  "willie-col-n-hector-lavoe": "/artista/willie-colon-hector-lavoe",
  "willie-col-n-ruben-blades": "/artista/willie-colon-ruben-blades",
  "wind-fire-earth": "/artista/earth-wind-fire",
};

/**
 * Href for a style tag's hub page. Resolves redirected slugs to their final
 * destination and country tags to /pais/<slug>, so no generated link needs a
 * 308 hop. Falls through to /estilo/<slug> for the ordinary case.
 */
export function estiloHref(slug: string): string {
  const redirected = ESTILO_REDIRECT_TARGETS[slug];
  if (redirected) return redirected;
  const pais = COUNTRY_TAG_TO_PAIS_SLUG[slug];
  if (pais) return `/pais/${pais}`;
  return `/estilo/${slug}`;
}
